export { default as DashboardPage } from './DashboardPage'
export { default as InventoryPage } from './InventoryPage'
export { default as MenuBuilderPage } from './MenuBuilderPage'
export { default as LoginPage } from './LoginPage'
export { default as ReportsPage } from './ReportsPage'
export { default as SuppliersPage } from './SuppliersPage'
